### PR TITLE
Optional ticketId and summary attributes

### PR DESCRIPTION
**Pull request by kassner**
This fixes an error when running functional tests:

```
Invalid Document
Element 'testCase': The attribute 'summary' is required but missing.
Line: 4

Element 'testCase': The attribute 'ticketId' is required but missing.
Line: 4
```

### CODE REVIEW

**Comment by lanken** [comment]
Hi @kassner, summary and ticketId attributes for test cases have been set as required intentionally, in order to control created tests.
Could you, please, specify running what tests did you face with such error?

**Comment by kassner** [comment]
@lanken I'm facing this error with my own tests, for obvious reasons. I would not have a ticketId for my own tests. Anyway, a lot of `testCases` does not have those attributes (and I guess they won't even run, I didn't ran the entire suite to be sure) like Backup, Fedex, Dhl, Weee, almost all `NavigateMenuTest.xml` files, etc.

**Comment by lanken** [comment]
As for test case *.xml files without this attribute after merging with original file they will be present.
As for your request, I guess we can set ticketId as optional attribute, but leave summary as required.
In order to process your pull request,please, merge the latest develop and update CHANGELOG.md with something like 'Set ticketId attribute for variations as optional'

**Comment by kassner** [comment]
@lanken great! I've pushed the modifications as requested.

Thanks!

**Comment by lanken** [comment]
@kassner thanks for contribution.

**Pull request merged**
